<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Detail_paket extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Detail_paket_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'detail_paket/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'detail_paket/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'detail_paket/index.html';
            $config['first_url'] = base_url() . 'detail_paket/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Detail_paket_model->total_rows($q);
        $detail_paket = $this->Detail_paket_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'detail_paket_data' => $detail_paket,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('admin/detail_paket/detail_paket_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Detail_paket_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_paket' => $row->id_paket,
		'tahun' => $row->tahun,
		'nip' => $row->nip,
	    );
            $this->load->view('admin/detail_paket/detail_paket_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('detail_paket'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('detail_paket/create_action'),
	    'id_paket' => set_value('id_paket'),
	    'tahun' => set_value('tahun'),
	    'nip' => set_value('nip'),
	);
        $this->load->view('admin/detail_paket/detail_paket_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nip' => $this->input->post('nip',TRUE),
	    );

            $this->Detail_paket_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('detail_paket'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Detail_paket_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('detail_paket/update_action'),
		'id_paket' => set_value('id_paket', $row->id_paket),
		'tahun' => set_value('tahun', $row->tahun),
		'nip' => set_value('nip', $row->nip),
	    );
            $this->load->view('admin/detail_paket/detail_paket_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('detail_paket'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_paket', TRUE));
        } else {
            $data = array(
		'nip' => $this->input->post('nip',TRUE),
	    );

            $this->Detail_paket_model->update($this->input->post('id_paket', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('detail_paket'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Detail_paket_model->get_by_id($id);

        if ($row) {
            $this->Detail_paket_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('detail_paket'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('detail_paket'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nip', 'nip', 'trim|required|numeric');

	$this->form_validation->set_rules('id_paket', 'id_paket', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Detail_paket.php */
/* Location: ./application/controllers/Detail_paket.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-12 08:45:11 */
/* http://harviacode.com */
