<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jenis_pekerjaan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jenis_pekerjaan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'jenis_pekerjaan/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'jenis_pekerjaan/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'jenis_pekerjaan/index.html';
            $config['first_url'] = base_url() . 'jenis_pekerjaan/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Jenis_pekerjaan_model->total_rows($q);
        $jenis_pekerjaan = $this->Jenis_pekerjaan_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'jenis_pekerjaan_data' => $jenis_pekerjaan,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('admin/jenis_pekerjaan/jenis_pekerjaan_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Jenis_pekerjaan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'nama_jenis' => $row->nama_jenis,
	    );
            $this->load->view('admin/jenis_pekerjaan/jenis_pekerjaan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenis_pekerjaan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jenis_pekerjaan/create_action'),
	    'id' => set_value('id'),
	    'nama_jenis' => set_value('nama_jenis'),
	);
        $this->load->view('admin/jenis_pekerjaan/jenis_pekerjaan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
        	$max=$this->db->query("SELECT MAX(CAST(id AS INT)) as max FROM jenis_pekerjaan")->result();
        	$max=$max[0]->max+1;
            $data = array(
				'id' => $max,
		'nama_jenis' => $this->input->post('nama_jenis',TRUE),
	    );

            $this->Jenis_pekerjaan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jenis_pekerjaan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jenis_pekerjaan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jenis_pekerjaan/update_action'),
		'id' => set_value('id', $row->id),
		'nama_jenis' => set_value('nama_jenis', $row->nama_jenis),
	    );
            $this->load->view('admin/jenis_pekerjaan/jenis_pekerjaan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenis_pekerjaan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'nama_jenis' => $this->input->post('nama_jenis',TRUE),
	    );

            $this->Jenis_pekerjaan_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jenis_pekerjaan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Jenis_pekerjaan_model->get_by_id($id);

        if ($row) {
            $this->Jenis_pekerjaan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jenis_pekerjaan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jenis_pekerjaan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_jenis', 'nama jenis', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jenis_pekerjaan.php */
/* Location: ./application/controllers/Jenis_pekerjaan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-12 08:45:11 */
/* http://harviacode.com */
