<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Minggu extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Minggu_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'minggu/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'minggu/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'minggu/index.html';
            $config['first_url'] = base_url() . 'minggu/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Minggu_model->total_rows($q);
        $minggu = $this->Minggu_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'minggu_data' => $minggu,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('admin/minggu/minggu_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Minggu_model->get_by_id($id);
        if ($row) {
            $data = array(
		'bulan' => $row->bulan,
		'minggu' => $row->minggu,
	    );
            $this->load->view('admin/minggu/minggu_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('minggu'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('minggu/create_action'),
	    'bulan' => set_value('bulan'),
	    'minggu' => set_value('minggu'),
	);
        $this->load->view('admin/minggu/minggu_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Minggu_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('minggu'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Minggu_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('minggu/update_action'),
		'bulan' => set_value('bulan', $row->bulan),
		'minggu' => set_value('minggu', $row->minggu),
	    );
            $this->load->view('admin/minggu/minggu_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('minggu'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('bulan', TRUE));
        } else {
            $data = array(
	    );

            $this->Minggu_model->update($this->input->post('bulan', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('minggu'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Minggu_model->get_by_id($id);

        if ($row) {
            $this->Minggu_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('minggu'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('minggu'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('bulan', 'bulan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Minggu.php */
/* Location: ./application/controllers/Minggu.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-12 08:45:12 */
/* http://harviacode.com */
